### ISSUE TITLE
crytocurrency readme needs to show how to obtain a twitter token

### ISSUE THREAD

**Issue by dbrimley** [hazelcast/jet-demos#15]
Not everyone will know about twitter tokens to gain access to the twitter API.

We need to put a section in the readme with links and a description of how to obtain this.

**Comment by dbrimley** [comment]
Same goes for reddit and secret keys. We need to make this as easy as possible for people to use.

**Comment by eminn** [comment]
Fixed via https://github.com/hazelcast/jet-demos/commit/8487c704199533fcf7b0a6b37df4907073ce1e7b
